import LegalPage from './LegalPage.jsx'

const email = 'voltsnbits26@gmail.com'

export default function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Privacy policy"
      title="Privacy Policy"
      intro="Effective Date: 26 September 2026 · Last Updated: 26 September 2026"
    >
      <section><h2>1. Introduction</h2><p>Volts&Bits respects your privacy and is committed to handling personal information responsibly.</p><p>This Privacy Policy explains what information we collect, why we collect it, how we use it, and the choices available to you when you interact with Volts&Bits.</p></section>
      <section><h2>2. Information We Collect</h2><p>When you submit a project inquiry, we may collect:</p><ul><li>Full name</li><li>Email address</li><li>Telephone/WhatsApp contact details if provided</li><li>University or tertiary institution</li><li>Programme or department</li><li>Project stage</li><li>Project topic or idea</li><li>Description of the technical problem</li><li>Project deadline</li><li>Requested services</li><li>Other information you voluntarily provide</li></ul><p>We ask students to avoid submitting unnecessary sensitive personal information through the inquiry form.</p></section>
      <section><h2>3. How We Collect Information</h2><p>Our initial project inquiry process uses <strong>Google Forms</strong>.</p><p>When you submit information through our inquiry form, the information is transmitted to and stored/processed using Google's services.</p><p>You should review Google's applicable privacy practices before submitting information through the form.</p></section>
      <section><h2>4. Why We Collect Your Information</h2><p>We use submitted information to:</p><ul><li>Understand your project needs</li><li>Evaluate whether we can assist you</li><li>Contact you about your inquiry</li><li>Discuss project scope</li><li>Prepare service proposals</li><li>Plan agreed project work</li><li>Communicate about ongoing services</li><li>Maintain appropriate business records</li><li>Improve our services</li></ul><p>We do not collect personal information simply because it is available. The information we request should be relevant to the purpose for which it is collected.</p><p>This approach is consistent with Ghana's Data Protection Act, which requires personal information processing to be lawful, reasonable, and not excessive in relation to its purpose.</p></section>
      <section><h2>5. Legal Basis for Processing</h2><p>Where applicable, we may process personal information based on:</p><ul><li>Your consent</li><li>Steps taken at your request before entering into an agreement</li><li>Performance of an agreement</li><li>Compliance with a legal obligation</li><li>A legitimate interest that is not overridden by your privacy rights</li></ul><p>You may object to certain processing where applicable under Ghanaian law.</p></section>
      <section><h2>6. How We Use Project Information</h2><p>Information about your project may be accessed by the people directly involved in providing the agreed Volts&Bits service.</p><p>We do not intentionally sell student personal information to third parties.</p><p>We do not use students' project ideas as public case studies without appropriate permission.</p></section>
      <section><h2>7. Third-Party Services</h2><p>We currently use or may use third-party services to operate parts of our business.</p><p><strong>Google Forms / Google services:</strong> used for collecting project inquiries.</p><p>Other third-party services may be introduced as the business develops. Where third-party services process information on our behalf, we will take reasonable steps to use appropriate providers and protect information shared with them.</p></section>
      <section><h2>8. Data Security</h2><p>We take reasonable technical and organizational measures to protect personal information against unauthorized access, loss, misuse, alteration, or disclosure.</p><p>However, no internet-based transmission or storage system can be guaranteed to be completely secure.</p></section>
      <section><h2>9. Data Retention</h2><p>We retain personal information only for as long as reasonably necessary for the purposes for which it was collected, including providing services, maintaining business records, resolving disputes, and complying with applicable legal obligations.</p><p>When information is no longer reasonably required, we will take appropriate steps to delete, destroy, or anonymize it where practicable.</p></section>
      <section><h2>10. Your Privacy Rights</h2><p>Subject to applicable law, you may have rights to:</p><ul><li>Request access to personal information we hold about you</li><li>Ask us to correct inaccurate information</li><li>Object to certain processing</li><li>Request deletion where applicable</li><li>Withdraw consent where processing is based on consent</li><li>Ask questions about how your information is being processed</li></ul><p>Ghana's Data Protection Act provides data subjects with rights relating to access to their personal information and information about its processing.</p></section>
      <section><h2>11. How to Make a Privacy Request</h2><p>To make a privacy-related request, contact:</p><address>Volts&Bits<br />Email: <a href={`mailto:${email}`}>{email}</a></address><p>Please provide enough information for us to identify the relevant inquiry or information.</p></section>
      <section><h2>12. Student Project Confidentiality</h2><p>Project ideas, research directions, technical designs, source code, datasets, and other project materials submitted to Volts&Bits may contain confidential information.</p><p>We will take reasonable measures to protect such information and will use it primarily for the purposes of providing the requested service.</p><p>Students should not submit passwords, authentication credentials, financial account information, or other unnecessary highly sensitive information through the inquiry form.</p></section>
      <section><h2>13. Children's Information</h2><p>Volts&Bits currently targets <strong>tertiary-level students and final-year projects</strong>.</p><p>Our services and inquiry process are not intentionally directed toward children.</p><p>If we become aware that we have collected personal information from a person who is not eligible to use our services, we may take reasonable steps to delete the information where appropriate.</p></section>
      <section><h2>14. Cookies and Website Technologies</h2><p>The Volts&Bits website may use basic browser technologies necessary for website operation.</p><p>If analytics, advertising, tracking technologies, or other non-essential cookies are introduced in the future, this Privacy Policy will be updated accordingly where required.</p></section>
      <section><h2>15. International Processing</h2><p>Because third-party technology providers such as Google may process information using infrastructure outside Ghana, information submitted through our inquiry form may be processed outside Ghana.</p><p>Where applicable, Volts&Bits will take reasonable steps to address relevant data-protection requirements.</p></section>
      <section><h2>16. Data Breaches</h2><p>If Volts&Bits becomes aware of a personal-data security incident, we will assess the incident and take appropriate steps under applicable law, including any required notifications.</p></section>
      <section><h2>17. Changes to This Privacy Policy</h2><p>We may update this Privacy Policy as our services, technology, or legal obligations change.</p><p>The latest version will be published on the website with an updated effective/last-updated date.</p></section>
      <section><h2>18. Contact</h2><p>For privacy questions or requests:</p><address>Volts&Bits<br /><br />Email: <a href={`mailto:${email}`}>{email}</a></address></section>
    </LegalPage>
  )
}
