import LegalPage from './LegalPage.jsx'

const email = 'voltsnbits26@gmail.com'

export default function TermsAndConditions() {
  return (
    <LegalPage
      eyebrow="Terms & conditions"
      title="Terms & Conditions"
      intro="Effective Date: 26 September 2026 · Last Updated: 26 September 2026"
    >
      <section><h2>1. About Volts&Bits</h2><p>Volts&Bits is a final-year project support and technical mentorship service.</p><p>We support tertiary students with research guidance, project discovery, technical planning, software and IoT development, AI/ML integration, implementation support, documentation guidance, and project presentation/defense preparation.</p><p>Volts&Bits is currently operating as an unregistered business/brand. Nothing on this website should be interpreted as representing Volts&Bits as an incorporated company or registered legal entity.</p></section>
      <section><h2>2. Acceptance of These Terms</h2><p>By using the Volts&Bits website, submitting a project inquiry, or engaging our services, you acknowledge that you have read and understood these Terms and agree to be bound by them.</p><p>If you do not agree with these Terms, please do not use our services.</p></section>
      <section><h2>3. Eligibility</h2><p>Volts&Bits currently provides its services to <strong>tertiary-level students</strong>, particularly students working on final-year academic projects.</p><p>You are responsible for providing accurate information about yourself, your institution, programme, project, and academic requirements.</p></section>
      <section><h2>4. Our Services</h2><p>Depending on the student's needs and agreed scope, Volts&Bits may provide:</p><ul><li>Project idea discovery and refinement</li><li>Research direction and literature/gap analysis</li><li>Problem-statement development</li><li>Technical architecture and technology selection</li><li>Software development guidance</li><li>AI and machine-learning integration</li><li>Web and mobile application development support</li><li>IoT and hardware/software integration</li><li>Debugging and implementation guidance</li><li>Documentation and technical-report guidance</li><li>Presentation and project-defense preparation</li></ul><p>The specific services, deliverables, timelines, and fees will be agreed upon with the student before work begins.</p></section>
      <section><h2>5. Mentorship and Academic Integrity</h2><p>Volts&Bits exists to <strong>help students understand, develop, and confidently defend their own work</strong>.</p><p>Our services are not intended to facilitate academic dishonesty, plagiarism, impersonation, fabrication of research, or submission of work that a student falsely represents as entirely their own.</p><p>Students remain responsible for:</p><ul><li>Understanding their project</li><li>Reviewing and approving work produced with our assistance</li><li>Following their institution's academic rules</li><li>Properly acknowledging external sources and assistance where required</li><li>Ensuring that their final submission complies with their institution's policies</li></ul><p>We may decline requests that we reasonably believe would facilitate academic misconduct.</p></section>
      <section><h2>6. Student Responsibilities</h2><p>Students must provide accurate and complete information relevant to their project.</p><p>Students are also responsible for:</p><ul><li>Providing required project requirements and specifications</li><li>Providing necessary datasets, documentation, or technical information they have the right to share</li><li>Reviewing project outputs</li><li>Meeting agreed deadlines</li><li>Communicating changes in project requirements promptly</li><li>Following applicable university or institutional requirements</li></ul></section>
      <section><h2>7. Project Scope and Changes</h2><p>Services are provided according to an agreed scope.</p><p>If a student requests substantial changes, additional features, additional research, or work outside the original scope, Volts&Bits may reassess the timeline and applicable fee before proceeding.</p></section>
      <section><h2>8. Fees and Payment</h2><p>Fees are determined according to the scope, complexity, timeline, and technical requirements of the project.</p><p>Payment arrangements will be communicated directly to the student before work begins.</p><p>At present, payment is handled <strong>directly/off-platform rather than through an online payment system on the website</strong>.</p><p>No payment should be considered accepted until Volts&Bits confirms the agreed payment arrangement.</p></section>
      <section><h2>9. Timelines</h2><p>Project timelines depend on project complexity, scope, student responsiveness, availability of required materials, technical dependencies, and agreed milestones.</p><p>Volts&Bits will communicate an estimated timeline when the project scope is agreed. Deadlines imposed by a student's institution should be communicated as early as possible.</p></section>
      <section><h2>10. Academic Results</h2><p>Volts&Bits does not guarantee a particular academic grade, project approval, supervisor approval, successful defense, publication, funding, employment, or other academic/professional outcome.</p><p>Our role is to provide technical guidance, mentorship, and project support.</p></section>
      <section><h2>11. Intellectual Property</h2><p>Unless otherwise agreed in writing, students retain ownership of their original project materials and information they provide to Volts&Bits.</p><p>Students must have the necessary rights or permissions to provide datasets, code, documents, images, or other materials to us.</p><p>Third-party software, libraries, datasets, APIs, models, and other resources remain subject to their respective licences and terms.</p></section>
      <section><h2>12. Confidentiality</h2><p>Volts&Bits will take reasonable steps to keep confidential project information shared by students and will not intentionally disclose such information to unrelated third parties except where the student authorizes disclosure, disclosure is necessary to provide an agreed service, disclosure is required by law, or disclosure is necessary to protect legal rights or safety.</p></section>
      <section><h2>13. Third-Party Services</h2><p>Our website may link to or use third-party services, including Google Forms and external technical resources.</p><p>Third-party services operate under their own terms and privacy policies. Volts&Bits is not responsible for the policies, security, availability, or practices of third-party services outside our control.</p></section>
      <section><h2>14. Website Use</h2><p>You agree not to:</p><ul><li>Use the website for unlawful purposes</li><li>Submit intentionally false information</li><li>Attempt to compromise website security</li><li>Interfere with website operation</li><li>Copy or misuse Volts&Bits branding or content without permission</li><li>Use our services to facilitate academic misconduct</li></ul></section>
      <section><h2>15. Limitation of Liability</h2><p>To the extent permitted by applicable Ghanaian law, Volts&Bits will not be responsible for indirect or consequential losses arising from the use of our website or services.</p><p>Nothing in these Terms excludes liability that cannot lawfully be excluded or limited.</p></section>
      <section><h2>16. Suspension or Termination</h2><p>Volts&Bits may decline, suspend, or terminate services where a student breaches these Terms, the requested work would facilitate academic misconduct, required information is materially misleading, the student fails to meet agreed payment obligations, continued work becomes technically or practically unreasonable, or termination is otherwise reasonably necessary.</p><p>Any outstanding financial obligations accrued before termination remain payable where applicable.</p></section>
      <section><h2>17. Changes to These Terms</h2><p>We may update these Terms from time to time. The updated version will be published on the website with a revised "Last Updated" date.</p></section>
      <section><h2>18. Governing Law</h2><p>These Terms are intended to be governed by the laws of the <strong>Republic of Ghana</strong>.</p><p>Where a dispute arises, the parties should first attempt to resolve it through good-faith communication before pursuing available legal remedies.</p></section>
      <section><h2>19. Contact</h2><p>For questions about these Terms:</p><address>Volts&Bits<br />Email: <a href={`mailto:${email}`}>{email}</a></address></section>
    </LegalPage>
  )
}
